### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by beckhamchen** [Tetratrio/stylegan2_pytorch#1]
Dear author,

When run_training, I have this error. Do you have any idea?

Original exception was:
Traceback (most recent call last):
  File "/home/chenchen/tools/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/chenchen/tools/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/chenchen/tools/pycharm-community-2017.3.1/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/chenchen/tools/pycharm-community-2017.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/chenchen/work/GAN/StyleGAN2_tet/run_training.py", line 857, in <module>
    main()
  File "/home/chenchen/work/GAN/StyleGAN2_tet/run_training.py", line 852, in main
    run(args)
  File "/home/chenchen/work/GAN/StyleGAN2_tet/run_training.py", line 820, in run
    trainer = get_trainer(args)
  File "/home/chenchen/work/GAN/StyleGAN2_tet/run_training.py", line 698, in get_trainer
    G, D = get_models(args)
  File "/home/chenchen/work/GAN/StyleGAN2_tet/run_training.py", line 664, in get_models
    **common_kwargs
  File "/home/chenchen/work/GAN/StyleGAN2_tet/stylegan2/models.py", line 826, in __init__
    'num_layers': 1
  File "/home/chenchen/work/GAN/StyleGAN2_tet/stylegan2/modules.py", line 1362, in __init__
    ConvUpLayer if use_up else ConvLayer, layer_kwargs, wrap=True, noise=noise))
  File "/home/chenchen/work/GAN/StyleGAN2_tet/stylegan2/modules.py", line 188, in _get_layer
    layer = layer_class(**kwargs)
TypeError: __init__() got multiple values for argument 'self'

**Comment by adriansahlman** [comment]
Hello!

What settings did you use when you ran that code? I can fix the problem if
I am able to reproduce the error. I know where it is happening but I am not
sure why. Because it sounds like the "kwargs" contains a value for the key
'self'. But that dictionary has already popped the 'self' key a few code
lines above.

layer_kwargs.pop('self')

That should have removed the keyword.

You can also try to run the code directly from the command-line instead of
using PyCharm because I have not tested it with PyCharm.

Lets try to solve it!

**Comment by beckhamchen** [comment]
Thanks for your instruction. I have soved problem. Another question is that how many iterations do your program need to train a face generator (FFHQ)?

**Comment by adriansahlman** [comment]
In the stylegan2 paper they iterate over 25 million images before stopping. With a batch size of 32 that means 781,250 iterations.

**Comment by beckhamchen** [comment]
Oh, such a long time. It will take almost two weeks for me. I will report the results after training. Thank you ! 

> In the stylegan2 paper they iterate over 25 million images before stopping. With a batch size of 32 that means 781,250 iterations.

**Comment by adriansahlman** [comment]
Yea, it takes very long to train! In the paper they used 8 V100 GPUs and trained for 9 days.

No problem, good luck!

**Comment by bindita** [comment]
@Tetratrio  Hi, after how many iterations should we expect to see a decent result if we train from scratch? Here is a plot of G_loss (red) and D_loss (blue) for a finetuning experiment (hence the initial dip). I don't see any visual improvements after 10,000 iterations and the discriminator loss also seems to be not helping. The results are decent but lack the high fidelity of the original paper results.

![loss](https://user-images.githubusercontent.com/43757801/89166045-4ae5af80-d52e-11ea-9130-fdf72286014b.png)

However, I am training on 2300 images, so the small dataset size is likely the issue. Also do you know why no VGG (perceptual) loss is used by stylegan?
